### ISSUE TITLE
CSS ordering from shared chunk not deterministic with multi entry points

### ISSUE THREAD

**Issue by ferdaber** [webpack-contrib/mini-css-extract-plugin#202]
Minimal reproduction repo (kind of): https://github.com/ferdaber/css-plugin-ordering-bug
Node: v9.11.1
OS: MacOS v10.12.6

With the latest version v0.4.1, in multiple-entry-points situations, I found that the CSS ordering is not deterministic. I set up a repo that "reproduces" the bug to the best of my ability (before getting stuck in Webpack internals). 

The gist of it is that in cases where a chunk is shared between multiple chunk groups, it's not always the case that the first chunk group actually has the CSS modules that we want to sort on, which results in this line returning `undefined` for the module index:
https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L393

Chunk groups:
* `entry-a~vendor`: has `a.js` and `shared_modules/other.js`
* `entry-b~vendor`: has `b.js`, `shared_modules/red.css` and `shared_modules/blue.css`

In my repo, I set it up so that anything in `shared_modules` is split out into a separate chunk, but have the entry points ordered such that the first chunk group contains no CSS modules (`entry-a`'s dependency tree only contains JS files but touches the `shared_modules` chunk group). This leads to the sorting mechanism as mentioned above to return `undefined` for a CSS module's index. 

The output in this repo still ended up having the correct ordering but I think it was because the `chunk.modulesIterable` set had the correct ordering at the time:

Output css/vendor.css:
```css
html {
  background: blue;
}
html {
  background: red;
}
```

Expected css/vendor.css:
```css
html {
  background: red;
}
html {
  background: blue;
}
```

To my understanding, `chunk.modulesIterable` is generated (or added) asynchronously so the ordering is not always guaranteed?

At this point I got stuck trying to get more information to submit to this issue, if a maintainer could offer me some guidance to what a better chunking strategy would be to work around this, or a fix for this, that would be super appreciated - thanks!

**Comment by dtothefp** [comment]
@evilebottnawi I can report a similar issue from the `v4.0.1` release. This is pretty much the exact same behavior I was seeing when upgrading to Webpack 4 and using the `extract-text` plugin.  

 I'm using PostCSS Loader with CSS modules. In development without extract text everything works as expected, although in prod when using extract text I see a duplication of the same compiled CSS module classes in the bundle and a regression in order of some classes. 

This seems to be happening in combination with using the 
- postcss-import module
- using `composes: ` via CSS loader

ex. the following css most likely occurs in various files throughout the application resulting in class duplication and changes in order

```css
@import 'config/common.css';
@import 'config/header.css';

.container {
  position: relative;
}

.cta-text {
  composes: heading-4 from 'helpers/typography.css';
}
```

This problem is in a large repo and I'm having problems replicating it in a minimal use case but when I do I will post a demo.

In the real life situation:

the order of css is wrong (`typography__heading-1` should be the base style, and then overwritten with the `Hero__heading`)
![image](https://user-images.githubusercontent.com/7387858/42352815-c239e1a0-808a-11e8-9f29-c80bd416f4ae.png)

Resulting from the following CSS when both `global.css` and `Hero.css` are extracted together into the same file:

```css
// global.css
@import 'helpers/typography.css';
```
```css
// Hero.css
.text-headline {
  composes: heading-1 from 'helpers/typography.css';
  color: var(--color-text);

  @media (--large-up) {
    width: 100%;
  }
}
```

```js
//main.js
import './global.css';
import Hero from `./Hero'; // where Hero.js imports Hero.css as css-module
```
