### ISSUE TITLE
cant load slick-theme.css

### ISSUE THREAD

**Issue by romainquellec** [webpack-contrib/mini-css-extract-plugin#282]
( I'm using next7, last version with everything )

I'm trying to load the slick-theme.css (https://github.com/kenwheeler/slick/blob/master/slick/slick-theme.css) but i'm getting : 

```
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type.
```

When I delete this part: 

```
@charset 'UTF-8';
/* Slider */
.slick-loading .slick-list
{
    background: #fff url('./ajax-loader.gif') center center no-repeat;
}

/* Icons */
@font-face
{
    font-family: 'slick';
    font-weight: normal;
    font-style: normal;

    src: url('./fonts/slick.eot');
    src: url('./fonts/slick.eot?#iefix') format('embedded-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('truetype'), url('./fonts/slick.svg#slick') format('svg');
}
```
everything is fine.

**Comment by evilebottnawi** [comment]
@romainquellec looks you have invalid configuration, please provide minimum reproducible test repo

**Comment by romainquellec** [comment]
I didn't have a min repo, sorry.
Btw, i'm apparently not the only one : https://github.com/zeit/next.js/issues/5225

**Comment by dustinbrink** [comment]
I too have encountered this error importing my own less in a component.

`ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <?xml version="1.0" encoding="UTF-8"?>
| <svg width="283px" height="272px" viewBox="0 0 283 272" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
|     `

It has something to do with using an svg background image, because I can get it to compile if I comment out this line

`background: #0f1e46 url(../static/images/particles-pattern-2.svg) no-repeat;`

**Comment by dustinbrink** [comment]
I was able to fix my problem above by requesting the svg from root, like so

`background: #0f1e46 url(/static/images/particles-pattern-2.svg) no-repeat;`

Hopefully this might be useful

**Comment by dptoot** [comment]
I am having the same issue.  removing the following code from our style sheet to load our custom icons solves the issue.

```css
/*
@font-face {
  font-family: "AXLcons";
  src: url("./fonts/AXLcons.eot");
  src: url("./fonts/AXLcons.eot#iefix") format("embedded-opentype"), url("./fonts/AXLcons.woff2") format("woff2"), url("./fonts/AXLcons.woff") format("woff"), url("./fonts/AXLcons.ttf") format("truetype"), url("./fonts/AXLcons.svg#AXLcons") format("svg"); }
*/
```
