### ISSUE TITLE
Styles are getting duplicated in development mode

### ISSUE THREAD

**Issue by just-boris** [webpack-contrib/mini-css-extract-plugin#283]
I have the following files:

**common.css**
```css
.test {
    color: purple; /* just some styles to test */
}
```

**component.css**
```css
@import './common.css';
```

**styles.css**
```css
@import "./common.css";
@import "./component.css";
```

In the output bundle I have the following:

```css
.test {
    color: purple;
}

.test {
    color: purple;
}
```

The references to `common.css` are not merged and the content is rendered twice. This happening only in `mode: "development"`, and is actually caused by `NamedModulesPlugin`. Removing this module from config fixes the issue.

P.S. there is a repository, that you can checkout locally and reproduce the issue: https://github.com/just-boris/mini-css-extract-plugin-283
