### ISSUE TITLE
@charset rules

### ISSUE THREAD

**Issue by ryuran** [webpack-contrib/mini-css-extract-plugin#310]
Hello,

One of my source’s css start by:
```css
@charset "UTF-8";
```
When I use `mini-css-extract-plugin` thos css is concatenated with others and the final file contain the `@charset` rule in the middle of the file and there is no `@charset` rule at the top.

How to have only one `@charset` rule at the top of final css file ?

**Comment by evilebottnawi** [comment]
@ryuran you can use `cssnano` to remove unused `@charset`, this plugin just extract `css`

**Comment by ryuran** [comment]
@evilebottnawi ok for inside css but how to keep a charset rules on top of final extracted file?

**Comment by evilebottnawi** [comment]
@ryuran i can't understand you, what you mean `inside css`

**Comment by ryuran** [comment]
first.css file
```css
.first {
  color: blue;
}
```
second.css file:
```css
@charset "UTF-8";
.second {
  color: red;
}
``` 
js:
```javascript
require('first.css')
require('second.css')
```

extracted css by `mini-css-extract-plugin`:
```css
.first {
  color: blue;
}
@charset "UTF-8";
.second {
  color: red;
}
```

If I use cssnano, I can easily remove this `@charset "UTF-8";` from every css sources.
But I don’t know how to add `@charset "UTF-8";` at beginning of extracted css.
