### ISSUE TITLE
Order problem

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/mini-css-extract-plugin#555]
- Operating System: Ubuntu 16.04.5 LTS
- Node Version: v10.19.0
- NPM Version: 6.13.4
- webpack Version: 4.42.1
- css-loader Version: 3.4.1 (used in latest CRA https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/package.json)

### Expected Behavior

After dynamically importing component, which composes css class, that an already present component also composes, the existing component should preserve its styles.

![Screenshot from 2020-04-06 11 22 27](https://user-images.githubusercontent.com/14111857/78543876-98a91000-77f9-11ea-9458-e94a9d7a6619.png)

### Actual Behavior

After dynamically importing component `B`, components `C` styles get overriden. 

![Screenshot from 2020-04-06 11 22 52](https://user-images.githubusercontent.com/14111857/78544066-e160c900-77f9-11ea-805c-73f72cc50b30.png)

### Code

```
// index.module.css

.test {
    background-color: red;
    padding: 30px;
}
```
```
// b.module.css

.test2 {
    composes: test from '../index.module.css';
    background-color: blue;
}
```

```
// c.moodule.css

.test3 {
    composes: test from '../index.module.css';
    background-color: green;
}
```

**Result**:

```html
<head>
    <link rel="stylesheet" type="text/css" href="chunk-2.css">
    <script charset="utf-8" src="2.main.js"></script>
    <link rel="stylesheet" type="text/css" href="chunk-1.css">
    <script charset="utf-8" src="1.main.js"></script>
</head>
```

```css
// chunk-2.css

._2D6NmF3oNXamuyZ2z-z6-2 {
  background-color: red;
  padding: 30px;
}

._2vSpwQvfEWT-h3qiyUMFPO {
  background-color: green;
}
```

```css
// chunk-1.css

._2D6NmF3oNXamuyZ2z-z6-2 {
  background-color: red;
  padding: 30px;
}

._3IkLTxcAE-k8TWXxjYQrik {
  background-color: blue;
}
```

**Webpack config:**

```js
// webpack.config.js
...
    module: {
        rules: [
            {
                test: /\.module\.css$/i,
                use: [
                    { loader: MiniCssExtractPlugin.loader },
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                            importLoaders: 1,
                        },
                    },
                ],
            },
        ],
    },
...
```

### How Do We Reproduce?

For reproduction, see this minimal repo:
https://github.com/OHUSAR/css-modules-chunk-specificity-bug

_Originally posted by @OHUSAR in https://github.com/webpack-contrib/css-loader/issues/997#issuecomment-609688409_
