### ISSUE TITLE
Unnecessarily exports  module of css keyframes  

### ISSUE THREAD

**Issue by caihaihong** [webpack-contrib/mini-css-extract-plugin#578]
- Operating System:Windows x64
- Node Version:v12.13.1
- NPM Version:6.12.1
- webpack Version:"^4.44.1",
- mini-css-extract-plugin Version:"^0.11.0"

### Expected Behavior

It's unnecessarily to  exports module  of css keyframes  

### Actual Behavior

exports module  of  css keyframes  

### Code

```js
demo:  git@github.com:caihaihong/test.git
```

```js
(window["webpackJsonp"] = window["webpackJsonp"] || []).push([
  [0],
  [
    /* 0 */
    /***/ function (module, exports, __webpack_require__) {
      __webpack_require__(1);
      // Why do we run this function?
      // it returns {"sk-chase-dot":"initLoading__sk-chase-dot--1JdAA"}
      /***/
    },
  ],
  [[0, 1, 2]],
]);
```

```javascript
.initloading {
  width: 100%;
  height: 100vh;
}
.sk-chase-dot {
  animation: initLoading__sk-chase-dot--1JdAA 2s ease-in-out infinite both;
}
@keyframes initLoading__sk-chase-dot--1JdAA {
  to {
    transform: rotate(1turn);
  }
}
```

```javascript
(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[2],[
/* 0 */,
/* 1 */
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin
module.exports = {"sk-chase-dot":"initLoading__sk-chase-dot--1JdAA"};

/***/ })
]]);
```

```less
:global {
  .initloading {
    width: 100%;
    height: 100vh;
  }

  .sk-chase-dot:local {
    animation: sk-chase-dot 2s infinite ease-in-out both;
  }

  @keyframes sk-chase-dot {
    100% {
      transform: rotate(360deg);
    }
  }
}
```

![avatar](http://tattooonline.oss-cn-shenzhen.aliyuncs.com/ss/1.jpg)

![avatar](http://tattooonline.oss-cn-shenzhen.aliyuncs.com/ss/2.jpg)

![avatar](http://tattooonline.oss-cn-shenzhen.aliyuncs.com/ss/3.jpg)
