### ISSUE TITLE
How can I keep the css order in the css file when I use mini-css-extract-plugin？

### ISSUE THREAD

**Issue by choyongjoon** [webpack-contrib/mini-css-extract-plugin#58]
This issue is related to [the issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/200) from [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/200)

How can ensure `core.scss` (global style which is included in the entry file) is before `greenContainer.scss` (component style which is included in a component file)?

Test repo: https://github.com/choyongjoon/webpack4-css-modules

#### index.js
```javascript
import React from 'react'
import { render } from 'react-dom'

import App from 'App'
import 'styles/core.scss'

render(
  <App history={history} />,
  document.getElementById('root')
)
```

#### core.scss
``` sass
:global {
  @import '~normalize.css/normalize';

  // override-bootstrap
  .bg-primary {
    background-color: red;
  }
}
```

#### App.js
``` js
import React from 'react'

import GreenContainer from 'components/GreenContainer'

export class App extends React.Component {
  render () {
    return (
      <GreenContainer />
    )
  }
}

export default App
```

#### greenContainer.js
``` js
import React from 'react'

import classes from './GreenContainer.scss'

export default class GreenContainer extends React.Component {
  render () {
    return (
      <div className={`bg-primary ${classes.greenContainer}`} />
    )
  }
}
```

#### greenContainer.scss
``` sass
.greenContainer {
  height: 400px;
  // override core.scss
  background-color: green;
}
```

#### main.css
``` css
.GreenContainer__greenContainer{background-color:green;height:100%}
/*! normalize.css v8.0.0 | MIT License | github.com/necolas/normalize.css */
...
.bg-primary{background-color:red}
```
