### ISSUE TITLE
MiniCssFile emits `=` symbol to the end of the url

### ISSUE THREAD

**Issue by akoidan** [webpack-contrib/mini-css-extract-plugin#699]
- Operating System: MacOs bleeding edge
- Node Version: 12.10.0
- NPM Version: 6.10.3
- webpack Version: 4.46.0
- mini-css-extract-plugin Version: 1.3.6

### Expected Behavior

Hashes on included resources in css (e.g. url(font)) should be the same inside css and js file

### Actual Behavior
css files has this hash
```
src:url(https://static.pychat.org/font/fontello.eot?21a4cc50be58c1
f0d8b8941292120311=)
```
js file has this hash
```
/font/fontello.eot?21a4cc50be58c1f0d8b8941292120311
```

### Code
To reproduce we need 
1. To pass `publicPath` to MiniCssExtractPlugin options that is an absolute url
2. on fileLoader add name which has `[contenthash]` in it
```js
// webpack.config.js

module: {
 rules : [
   {
      test: /\.sass$/,
      use: [
         {
           loader: MiniCssExtractPlugin.loader,
           publicPath: "https://static.pychat.org"
         },
         'css-loader',
        sassOptionsGlobal,
      ]
   }
 ]
}
```

### How Do We Reproduce?

```
git clone https://github.com/akoidan/pychat
cd pychat
git checkout a8d6d3c3575674c35c12e167cd40e908a451f36c
cd frontend
cp pychat.org.json production.json
nvm use
yarn install
yarn prod
cat dist/sw.js # check asssets. e.g. fontello.woff2 /font/fontello.woff?214a56
cat dist/main.css # check asssets. e.g. fontello.woff2. in my repo it's url(https://static.pychat.org/font/fontello.woff?214a563509566562229f1193074cf803=) format("woff")
```
Tips:
If I remove public path option from extractminicss plugin this `=` symbol is no longer present
P.S> webpack config is located in builder.js

The diversion from origin source causes a lot of issues in service worker, since I rely that file assets should be the same.

**Comment by alexander-akait** [comment]
I think bug in `vue-loader`, we don't touch URLs and never add `=`

**Comment by akoidan** [comment]
@alexander-akait I think it's not related to vue-loader since, fonts are located in .sass files not .vue. If it's not miniextract-css it could be either `file-loader`, either `css-loader`. I tried to debug both but didn't find anything. Since this bug reproduces depending on options I pass in it I posted it here.

**Comment by alexander-akait** [comment]
> What do you think would be a proper place to post this issue?

Not sure, I need to debug it, try to find time in near future...

**Comment by alexander-akait** [comment]
WIP

**Comment by alexander-akait** [comment]
Weird, try to install and got the error `Cannot find module './production.json'`

**Comment by alexander-akait** [comment]
After adding `production.json`, I have code:

**dist/main.css**

```css
@font-face{font-family:'fontello';src:url(/font/fontello.eot?21a4cc);src:url(/font/fontello.eot?21a4cc) format("embedded-opentype"),url(/font/fontello.woff2?7549b5) format("woff2"),url(/font/fontello.woff?214a56) format("woff"),url(/font/fontello.ttf?103acd) format("truetype"),url(/font/fontello.svg?347cb6) format("svg");font-weight:normal;font-style:normal}
```

tested on Ubuntu Linux:
```bash
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
