### ISSUE TITLE
Duplicate <link> tags are added each time a chunk is import()ed

### ISSUE THREAD

**Issue by Kovensky** [webpack-contrib/mini-css-extract-plugin#8]
```js
// a.js
import('./b.js').then(() => { import('./b.js') })
```

```js
// b.js
import './b.css'
```

```css
/* b.css */
body {
  background: pink;
}
```

<img width="323" alt="image" src="https://user-images.githubusercontent.com/73085/36957706-9672d3d6-2079-11e8-9516-f2c6e528b1e5.png">

I'm not sure if this is a bug or a feature, though 🤔
